remote_theme: just-the-docs/just-the-docs
title: FreeNT
description: OpenWindows vanilla kernel
callouts:
  annotated-line:
    color: yellow
  warning:
    title: "Warning"
    color: yellow
  caution:
    title: "Caution"
    color: red
  new:
    title: "New"
    color: green
  info:
    title: "Info"
    color: blue
  note:
    title: "Note"
    color: blue
  tip:
    title: "Protip"
    color: green
gh_edit_link: true
gh_edit_link_text: "Edit this page"
gh_edit_repository: "https://github.com/freent-project/freent31-docs"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
mermaid:
  version: "9.3.0"
search.button: true
search.rel_url: false
